# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & ship APK to Firebase App Distribution"
  lane :android_firebase do
    sh "flutter pub get"
    sh "cd android && ./gradlew assembleRelease"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      testers: ENV["FIREBASE_TESTERS"],
      release_notes: "CI build #{Time.now.utc}",
      apk_path: "android/app/build/outputs/apk/release/app-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
