# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & ship Android release to Firebase App Distribution"
  lane :android_firebase do
    # Ensure flutter is available on CI (we'll install in the workflow)
    sh "cd .. && flutter pub get"

    # Build signed APK (ensure android/key.properties exists via CI step)
    sh "./gradlew assembleRelease"

    # Upload to Firebase App Distribution
    # Requires: FIREBASE_TOKEN or service account env, APP_ID, TESTERS/GROUPS
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],           # e.g. 1:1234567890:android:abc...
      testers: ENV["FIREBASE_TESTERS"],              # comma-separated emails
      release_notes: "CI auto-build #{Time.now.utc}",
      apk_path: "android/app/build/outputs/apk/release/app-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]                 # we install firebase cli in CI
    )
  end  
end
